### PR TITLE
Added JavaCorrectionAdvanced.java

### PR DESCRIPTION
**Pull request by PraveenKishore**
Added JavaCorrectionAdvanced.java and solved the advanced exercise sheet

### CODE REVIEW

**Comment by P1kachu** [comment]
Hey ! Thank you for your work !

Before merging, I would like you to append this file to the already existing Java correction, from where you will be able to put your nick too at the top of the file. It's simpler to reference files like this, and helps woth naming consistency.

**Comment by PraveenKishore** [comment]
Moved the code to CorrectionJava.java :+1:

**Comment by P1kachu** [comment]
Great. Thank you ! :octocat: 

Appart from the indentation issue that I can fix myself, do you have anything you want to add before merging ? Have you verified it worked correctly even in the new file ?

**Comment by PraveenKishore** [comment]
The already existing code has some ";" missing, fixed it. Also fixed the duplicate variable issue. The code is tested thoroughly. The advanced exercise code is working as expected. 
Sorry for the indentation issue, since I'm updating the code from a Windows machine, tab is twice as long.

**Comment by P1kachu** [comment]
No problem !

Thank you very much !

I'll merge them and verify indentation.

Thanks a lot again !

**Comment by PraveenKishore** [comment]
No mention, my pleasure!

**Pull request merged**
